### ISSUE TITLE
Node 16 deprecation

### ISSUE THREAD

**Issue by mateuszkwiecinski** [lwasyl/ftl-tests-results-action#22]
Not sure if `V3` version is compatible with Node 20, but in case it's not it may start failing the build, according to the warning:

> The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-java@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

**Comment by lwasyl** [comment]
Fixed in https://github.com/lwasyl/ftl-tests-results-action/releases/tag/v0.2.0
